### ISSUE TITLE
Jumping/fall sounds are constantly playing.

### ISSUE THREAD

**Issue by bkgktp** [oraxen/oraxen#1320]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

If I set the stone and wood sounds to be removed from sounds.yml for CustomBlock sounds and I want to use custom sounds in blocks, when I hover over the stone and wood blog, the jumping sound repeats in the same place. Minecraft only allows the jump sound to be played once on a block

https://streamable.com/iqoqhx

### Steps to reproduce

just try adding custom sound to the blocks.

### Plugin Version

<img width="271" alt="image" src="https://github.com/oraxen/oraxen/assets/101702786/543cbb59-4837-463d-af27-e0d5e3034a71">

### ProtocolLib Version

<img width="490" alt="image" src="https://github.com/oraxen/oraxen/assets/101702786/ba743ced-6baa-4adc-93c4-9f3db9fbf305">

### Server Software & Version

<img width="516" alt="image" src="https://github.com/oraxen/oraxen/assets/101702786/816f14c4-d6a1-46a6-ae99-1315b497bf36">

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by bkgktp** [comment]
I have mentioned this problem before, it is a very important problem for the use of the blocks, why is it not taken into account? @Boy0000

**Comment by Boy0000** [comment]
you opened this bugreport 8 hours ago? You will have to be patient, this is the first time someone reports this issue or really mentions it...

**Comment by bkgktp** [comment]
I have to say that this problem has been happening since you released the oraxene block sounds update and it is quite surprising that this bug has not been taken into account or noticed.

If people realize that the blocks are error-free and usable, it will be one more reason to choose oraxen, so I care that this simple but important problem is solved.

**Comment by Boy0000** [comment]
It will be gotten to in due time. It has not been reported therefore not fixed and it isnt my # 1 priority right now

**Comment by bkgktp** [comment]
Will this be fixed before version 2.0?

**Comment by Boy0000** [comment]
there is no ETA on any fix
it might or might not be
Feel free to open a PR if you want it fixed as soon as possible

**Comment by Boy0000** [comment]
fixed in 2.0
